context:
  version: "12.7.1"

package:
  name: commit-and-tag-version
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/commit-and-tag-version/-/commit-and-tag-version-${{ version }}.tgz
  sha256: 33602ca8ced3b6d1f74e54b01da02b8dc8fd03785e824833375992d564eb5101

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commit-and-tag-version --help

about:
  license: ISC
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: Fork of the excellent standard-version.
  homepage: https://github.com/absolute-version/commit-and-tag-version
  repository: https://github.com/absolute-version/commit-and-tag-version

extra:
  recipe-maintainers:
    - danielnachun
