context:
  version: "12.5.2"

package:
  name: commit-and-tag-version
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/commit-and-tag-version/-/commit-and-tag-version-${{ version }}.tgz
  sha256: f6fea077a2d32f77ec6001b70166e82555f1aaa7b33236c624f151ff4124a289

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commit-and-tag-version --help

about:
  license: ISC
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: Fork of the excellent standard-version.
  homepage: https://github.com/absolute-version/commit-and-tag-version
  repository: https://github.com/absolute-version/commit-and-tag-version

extra:
  recipe-maintainers:
    - danielnachun
