context:
  version: "13.1.0"

package:
  name: commit-and-tag-version
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/commit-and-tag-version/-/commit-and-tag-version-${{ version }}.tgz
  sha256: d3ec01399b89b20290d32a7ce3b896d708adae189742adb7c1607c9066d3be96

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commit-and-tag-version --help

about:
  license: ISC
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: Fork of the excellent standard-version.
  homepage: https://github.com/absolute-version/commit-and-tag-version
  repository: https://github.com/absolute-version/commit-and-tag-version

extra:
  recipe-maintainers:
    - danielnachun
