context:
  version: "13.1.2"

package:
  name: commit-and-tag-version
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/commit-and-tag-version/-/commit-and-tag-version-${{ version }}.tgz
  sha256: c1295c4bc453cc6f3c5d8848cbaed05a522b3be93a753fc44d5197461bc79a75

build:
  number: 0
  noarch: generic

requirements:
  build:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - commit-and-tag-version --help

about:
  license: ISC
  license_file:
    - LICENSE.txt
    - third-party-licenses.txt
  summary: Fork of the excellent standard-version.
  homepage: https://github.com/absolute-version/commit-and-tag-version
  repository: https://github.com/absolute-version/commit-and-tag-version

extra:
  recipe-maintainers:
    - danielnachun
